### PR TITLE
refactor to fadecandy_driver / fadecandy_msgs

### PR DESCRIPTION
**Pull request by reinzor**
- Separated msgs to *_msgs package
- Separeted driver to *_driver package
- PEP8 styling refactor
- Added info diagnostics with serial number

### CODE REVIEW

**Comment by reinzor** [comment]
Last commit changes the RGBA range from 0..1 so that this is aligned with for example the visualization msgs

**Comment by jonbinney** [comment]
Oh interesting.... 0 to 1 makes much more sense than 0 to 255... i don't know why I had it set to that.

@reinzor thanks for doing this! This PR looks good; I just need to test it out. Will try to do that today.

**Comment by jonbinney** [comment]
Seems to work! I want to do a bit more testing; will merge today or tomorrow.

**Review by jonbinney — APPROVED** [review]
LGTM

**Comment by jonbinney** [comment]
Tested on a robot, lights made pretty colors. Merging.

**Comment by reinzor** [comment]
Great!

**Pull request merged**
